config/routes.rb
Rails.application.routes.draw do
  resources :properties do
    get :autocomplete_seller_name, :on => :collection
  end
  resources :buyers
  devise_for :users
  get 'home/index'

  resources :sellers

  root to: 'home#index'

end

app/models/buyer.rb
class Buyer < ActiveRecord::Base
  belongs_to :user
end

app/models/porfolio.rb
class Porfolio < ActiveRecord::Base
  belongs_to :seller
  belongs_to :property
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  belongs_to :seller
  belongs_to :property
end

app/models/property.rb
class Property < ActiveRecord::Base
  has_many :portfolios
  has_many :sellers, through: :portfolios
  belongs_to :user
end

app/models/seller.rb
class Seller < ActiveRecord::Base
  has_many :portfolios
  has_many :properties, through: :portfolios
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :sellers
  has_many :buyers
  has_many :properties

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  before_action :set_buyer, only: [:show, :edit, :update, :destroy]

  # GET /buyers
  # GET /buyers.json
  def index
    @buyers = Buyer.all
  end

  # GET /buyers/1
  # GET /buyers/1.json
  def show
  end

  # GET /buyers/new
  def new
    @buyer = Buyer.new
  end

  # GET /buyers/1/edit
  def edit
  end

  # POST /buyers
  # POST /buyers.json
  def create
    @buyer = Buyer.new(buyer_params)

    respond_to do |format|
      if @buyer.save
        format.html { redirect_to @buyer, notice: 'Buyer was successfully created.' }
        format.json { render :show, status: :created, location: @buyer }
      else
        format.html { render :new }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buyers/1
  # PATCH/PUT /buyers/1.json
  def update
    respond_to do |format|
      if @buyer.update(buyer_params)
        format.html { redirect_to @buyer, notice: 'Buyer was successfully updated.' }
        format.json { render :show, status: :ok, location: @buyer }
      else
        format.html { render :edit }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buyers/1
  # DELETE /buyers/1.json
  def destroy
    @buyer.destroy
    respond_to do |format|
      format.html { redirect_to buyers_url, notice: 'Buyer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buyer
      @buyer = Buyer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buyer_params
      params.require(:buyer).permit(:name, :last_name, :nif, :email, :telephone1, :telephone2, :idioma, :adress, :city, :country, :postal_code, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_user!

  def index
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]
  autocomplete :seller, :name

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:title, :subtitle, :description, :size, :type, :address, :city, :country, :operation_type, :extras, :user_id)
    end
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  before_action :set_seller, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!



  # GET /sellers
  # GET /sellers.json
  def index
    @sellers = Seller.all
  end

  # GET /sellers/1
  # GET /sellers/1.json
  def show
  end

  # GET /sellers/new
  def new
    @seller = Seller.new
  end

  # GET /sellers/1/edit
  def edit
  end

  # POST /sellers
  # POST /sellers.json
  def create
    @seller = Seller.new(seller_params)

    respond_to do |format|
      if @seller.save
        format.html { redirect_to @seller, notice: 'Seller was successfully created.' }
        format.json { render :show, status: :created, location: @seller }
      else
        format.html { render :new }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sellers/1
  # PATCH/PUT /sellers/1.json
  def update
    respond_to do |format|
      if @seller.update(seller_params)
        format.html { redirect_to @seller, notice: 'Seller was successfully updated.' }
        format.json { render :show, status: :ok, location: @seller }
      else
        format.html { render :edit }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sellers/1
  # DELETE /sellers/1.json
  def destroy
    @seller.destroy
    respond_to do |format|
      format.html { redirect_to sellers_url, notice: 'Seller was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seller
      @seller = Seller.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seller_params
      params.require(:seller).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/buyers/edit.html.erb
<h1>Editing Buyer</h1>

<%= render 'form' %>

<%= link_to 'Show', @buyer %> |
<%= link_to 'Back', buyers_path %>

app/views/buyers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Buyers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Last name</th>
      <th>Nif</th>
      <th>Email</th>
      <th>Telephone1</th>
      <th>Telephone2</th>
      <th>Idioma</th>
      <th>Adress</th>
      <th>City</th>
      <th>Country</th>
      <th>Postal code</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buyers.each do |buyer| %>
      <tr>
        <td><%= buyer.name %></td>
        <td><%= buyer.last_name %></td>
        <td><%= buyer.nif %></td>
        <td><%= buyer.email %></td>
        <td><%= buyer.telephone1 %></td>
        <td><%= buyer.telephone2 %></td>
        <td><%= buyer.idioma %></td>
        <td><%= buyer.adress %></td>
        <td><%= buyer.city %></td>
        <td><%= buyer.country %></td>
        <td><%= buyer.postal_code %></td>
        <td><%= buyer.user %></td>
        <td><%= link_to 'Show', buyer %></td>
        <td><%= link_to 'Edit', edit_buyer_path(buyer) %></td>
        <td><%= link_to 'Destroy', buyer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Buyer', new_buyer_path %>

app/views/buyers/new.html.erb
<h1>New Buyer</h1>

<%= render 'form' %>

<%= link_to 'Back', buyers_path %>

app/views/buyers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @buyer.name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @buyer.last_name %>
</p>

<p>
  <strong>Nif:</strong>
  <%= @buyer.nif %>
</p>

<p>
  <strong>Email:</strong>
  <%= @buyer.email %>
</p>

<p>
  <strong>Telephone1:</strong>
  <%= @buyer.telephone1 %>
</p>

<p>
  <strong>Telephone2:</strong>
  <%= @buyer.telephone2 %>
</p>

<p>
  <strong>Idioma:</strong>
  <%= @buyer.idioma %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @buyer.adress %>
</p>

<p>
  <strong>City:</strong>
  <%= @buyer.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @buyer.country %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @buyer.postal_code %>
</p>

<p>
  <strong>User:</strong>
  <%= @buyer.user %>
</p>

<%= link_to 'Edit', edit_buyer_path(@buyer) %> |
<%= link_to 'Back', buyers_path %>

app/views/home/index.html.erb
<br>

<!-- Primera fila de la Home -->

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-4">
      <div class="card card-block text-xs-center">
        <i class="fa fa-key fa-3x"></i>
        <h4 class="card-title">Clientes</h4>
        <p class="card-text">Da de alta a nuevos clientes o consulta los ya existentes.</p>
        <%= link_to "Clientes", buyers_path, class: "btn btn-primary" %>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="card card-block text-xs-center">
        <i class="fa fa-building fa-3x"></i>
        <h4 class="card-title">Propietarios</h4>
        <p class="card-text">Da de alta a nuevos propietarios o consulta los ya existentes.</p>
        <%= link_to "Propietarios", sellers_path, class: "btn btn-primary" %>
      </div>    </div>
    <div class="col-sm-4">
      <div class="card card-block text-xs-center">
        <i class="fa fa-home fa-3x"></i>
        <h4 class="card-title">Propiedades</h4>
        <p class="card-text">Da de alta a nuevas propiedades o consulta los ya existentes.</p>
        <%= link_to "Clientes", properties_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>


<!-- Segunda fila de la Home -->


  <div class="row">
    <div class="col-sm-4">
      <div class="card card-block text-xs-center">
        <i class="fa fa-map fa-3x"></i>
        <h4 class="card-title">Mapa</h4>
        <p class="card-text">Consulta el mapa con todas las propiedades localizadas.</p>
        <%= link_to "Mapa", properties_path, class: "btn btn-primary" %>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="card card-block text-xs-center">
        <i class="fa fa-briefcase fa-3x"></i>
        <h4 class="card-title">Asesores</h4>
        <p class="card-text">Consulta los asesores.</p>
        <%= link_to "Asesores", edit_user_registration_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer amc-footer">

  <div class="container">

    <center class="text-muted">Hecho por VayaWebs</center>

  </div>
  <!-- Latest compiled and minified JavaScript -->
  <script src="//cdnjs.cloudflare.com/ajax/libs/tether/1.3.1/js/tether.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/js/bootstrap.min.js" integrity="sha384-vZ2WRJMwsjRMW/8U7i6PWi6AlO1L79snBrmgiDpgIWJ82z8eA5lenwvxbMV1PAh7" crossorigin="anonymous"></script>



</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-light bg-faded">
  <div class="container-fluid">

    <div class="row">

      <div class="col-md-4">
        <!-- Logo -->
        <%= link_to image_tag('logo.png'), root_path, class:"navbar-brand" %>

      </div>


      <div class="col-md-8">
        <!-- Botón desplegable cuando es un dispositivo móvil: -->
        <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2">
          &#9776;
        </button>

        <!-- Todo lo que esté dentro del div navbar-toggleable-xs entrará en el botón de móvil   -->
        <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">

          <div class="row">

            <div class="col-md-12 amc_hello_col">
              <!-- Si el usuario está loggeado, le aparece su nombre y un link a su cienta, sino, la opcion de registrarse -->
              <% if user_signed_in? %>
                <div class="amc_hello">
                  <p>Hola <strong><%= current_user.email %></strong>.
                  <%= link_to 'Editar mis datos', edit_user_registration_path, :class => 'navbar-link' %> |
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></p>
                </div>
              <% else %>
                <div class="amc_hello">
                  <%= link_to "Regístrate", new_user_registration_path, :class => 'navbar-link'  %> |
                  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
                </div>
              <% end %>

            </div> <!-- End col-md-12 -->

          </div> <!-- End row -->

          <div class="row">

            <div class="col-md-12">

              <ul class="nav navbar-nav">
                <li class="nav-item active">
                  <%= link_to buyers_path, class:"nav-link" do %>
                    <i class="fa fa-key fa-fw"></i> Clientes
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to sellers_path, class:"nav-link" do %>
                    <i class="fa fa-building fa-fw"></i> Propietarios
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to properties_path, class:"nav-link" do %>
                    <i class="fa fa-home fa-fw"></i> Propiedades
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to root_path, class:"nav-link" do %>
                    <i class="fa fa-map fa-fw"></i> Mapa
                  <% end %>
                </li>
              </ul>
            </div> <!-- End col-md-12 -->
          </div> <!-- End row -->
        </div> <!-- End navbar-toggleable-xs -->

      </div> <!-- End col-md-8 -->
    </div> <!-- End row -->
  </div>
</nav>

app/views/properties/_form.html.erb
<div class="container">

  <%= form_for(@property) do |f| %>
    <% if @property.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

        <ul>
        <% @property.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title %><br>
      <%= f.text_field :title, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :subtitle %><br>
      <%= f.text_field :subtitle, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :description %><br>
      <%= f.text_field :description, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :size %><br>
      <%= f.text_field :size, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :type %><br>
      <%= f.text_field :type, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :address %><br>
      <%= f.text_field :address, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :city %><br>
      <%= f.text_field :city, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :country %><br>
      <%= f.text_field :country, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :operation_type %><br>
      <%= f.text_field :operation_type, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :extras %><br>
      <%= f.text_field :extras, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :user_id %><br>
      <%= f.text_field :user_id, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Propietario" %><br>

      <%= autocomplete_field_tag 'Buscar', '', autocomplete_seller_name_properties_path, :size => 75, class: "form-control" %>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <%= f.submit class:"btn btn-primary" %>
      </div>
      <div class="col-sm-6">
        <%= link_to 'Atrás', sellers_path, class:"btn btn-primary-outline" %>
      </div>
    </div>
  <% end %>
</div>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form' %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<h1>Listado de Propietarios</h1>
<%= link_to "Nueva Propiedad", new_property_path, class: "btn btn-primary amc-button-margin" %>
<br>

<div class="table-responsive">

  <table class="table table-striped">
    <thead class="thead-inverse">
      <tr>
        <th>Title</th>
        <th>Subtitle</th>
        <th>Description</th>
        <th>Size</th>
        <th>Type</th>
        <th>Address</th>
        <th>City</th>
        <th>Country</th>
        <th>Operation type</th>
        <th>Extras</th>
        <th>Consultor</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @properties.each do |property| %>
        <tr>
          <td><%= property.title %></td>
          <td><%= property.subtitle %></td>
          <td><%= property.description %></td>
          <td><%= property.size %></td>
          <td><%= property.type %></td>
          <td><%= property.address %></td>
          <td><%= property.city %></td>
          <td><%= property.country %></td>
          <td><%= property.operation_type %></td>
          <td><%= property.extras %></td>
          <td><%= property.user.email %></td>
          <td><%= link_to 'Show', property %></td>
          <td><%= link_to 'Edit', edit_property_path(property) %></td>
          <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div> <!-- End of table-responsive -->

<br>

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>Nueva Propiedad</h1>

<%= render 'form' %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @property.title %>
</p>

<p>
  <strong>Subtitle:</strong>
  <%= @property.subtitle %>
</p>

<p>
  <strong>Description:</strong>
  <%= @property.description %>
</p>

<p>
  <strong>Size:</strong>
  <%= @property.size %>
</p>

<p>
  <strong>Type:</strong>
  <%= @property.type %>
</p>

<p>
  <strong>Address:</strong>
  <%= @property.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @property.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @property.country %>
</p>

<p>
  <strong>Operation type:</strong>
  <%= @property.operation_type %>
</p>

<p>
  <strong>Extras:</strong>
  <%= @property.extras %>
</p>

<p>
  <strong>User:</strong>
  <%= @property.user.email %>
</p>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>

app/views/sellers/_form.html.erb
<div class="container">

  <%= form_for(@seller) do |f| %>
    <% if @seller.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@seller.errors.count, "error") %> prohibited this seller from being saved:</h2>

        <ul>
        <% @seller.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name, "Nombre" %><br>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :last_name, "Apellidos" %><br>
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :nif, "NIF" %><br>
      <%= f.text_field :nif, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :email, "E-mail" %><br>
      <%= f.text_field :email, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :telephone1, "Teléfono" %><br>
      <%= f.text_field :telephone1, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :telephone2 %><br>
      <%= f.text_field :telephone2, class: "form-control" %>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <%= f.submit class:"btn btn-primary" %>
      </div>
      <div class="col-sm-6">
        <%= link_to 'Atrás', sellers_path, class:"btn btn-primary-outline" %>
      </div>
    </div>
  <% end %>

</div>

app/views/sellers/index.html.erb
<h1>Listado de Propietarios</h1>
<%= link_to "Nuevo Propietario", new_seller_path, class: "btn btn-primary amc-button-margin" %>
<br>

<div class="table-responsive">

  <table class="table table-striped">
    <thead class="thead-inverse">
      <tr>
        <th>Name</th>
        <th>Apellidos</th>
        <th>Nif</th>
        <th>Email</th>
        <th>Telephone 1</th>
        <th>Telephone 2</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @sellers.each do |seller| %>
        <tr>
          <td><%= link_to seller.name, seller_path(seller) %></td>
          <td><%= link_to seller.last_name, seller_path(seller) %></td>
          <td><%= seller.nif %></td>
          <td><%= seller.email %></td>
          <td><%= seller.telephone1 %></td>
          <td><%= seller.telephone2 %></td>
          <td><%= link_to 'Editar', edit_seller_path(seller) %></td>
          <td><%= link_to 'Eliminar', seller, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div> <!-- End of table-responsive -->

<br>

<%= link_to "Nuevo Propietario", new_seller_path, class: "btn btn-primary", id: "my-id" %>

app/views/sellers/show.html.erb
<br>
<div class="container">

  <div class="card card-block">
    <div class="row">
      <div class="col-sm-6">

        <p>
          <strong>Name:</strong>
          <%= @seller.name %>
        </p>

        <p>
          <strong>Apellidos:</strong>
          <%= @seller.last_name %>
        </p>

        <p>
          <strong>Nif:</strong>
          <%= @seller.nif %>
        </p>
      </div>
      <div class="col-sm-6">
        <p>
          <strong>Email:</strong>
          <%= @seller.email %>
        </p>

        <p>
          <strong>Telephone:</strong>
          <%= @seller.telephone1 %>
        </p>

        <p>
          <strong>Telephone2:</strong>
          <%= @seller.telephone2 %>
        </p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-6">
      <%= link_to 'Editar', edit_seller_path(@seller), class:"btn btn-primary" %>

      <%= link_to 'Atrás', sellers_path, class:"btn btn-primary-outline" %>
    </div>
  </div>

</div> <!-- End of container -->

<br>



<h3>Propiedades de <%= @seller.name + " " + @seller.last_name %></h3>
  <div class="table-responsive">

    <table class="table table-striped">
      <thead class="thead-inverse">
        <tr>
          <th>Title</th>
          <th>Subtitle</th>
          <th>Description</th>
          <th>Size</th>
          <th>Type</th>
          <th>Address</th>
          <th>City</th>
          <th>Country</th>
          <th>Operation type</th>
          <th>Extras</th>
          <th>Consultor</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @seller.properties.each do |property| %>
          <tr>
            <td><%= property.title %></td>
            <td><%= property.subtitle %></td>
            <td><%= property.description %></td>
            <td><%= property.size %></td>
            <td><%= property.type %></td>
            <td><%= property.address %></td>
            <td><%= property.city %></td>
            <td><%= property.country %></td>
            <td><%= property.operation_type %></td>
            <td><%= property.extras %></td>
            <td><%= property.user.email %></td>
            <td><%= link_to 'Show', property %></td>
            <td><%= link_to 'Edit', edit_property_path(property) %></td>
            <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div> <!-- End of table-responsive -->



  <%= link_to 'Añadir propiedad', new_property_path(@seller), class:"btn btn-primary" %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>